# Generated by Django 5.0.5 on 2024-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_customer_id_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase')], max_length=20),
        ),
    ]
