# Generated by Django 5.0.5 on 2024-11-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_userinteraction_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='userinteraction',
            old_name='user',
            new_name='user_id',
        ),
    ]
