# Generated by Django 5.1.3 on 2024-11-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_product_userinteraction_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinteraction',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userinteraction',
            old_name='user_id',
            new_name='user',
        ),
    ]
